export const CATEGORIES = [
  { id: "cabos", label: "Cabos e Adaptadores" },
  { id: "audio", label: "Áudio" },
  { id: "perifericos", label: "Periféricos" },
  { id: "energia", label: "Energia e Proteção" },
  { id: "cuidados", label: "Cuidados Pessoais" },
];

export const PRODUCTS = [
  // CABOS
  {
    id: "cabo-p2",
    name: "Cabo P2 3.5mm",
    category: "cabos",
    price: 19.9,
    image: "/assets/img/cabo-p2.webp",
    specs: { tipo: "P2" },
    description: "Cabo de áudio estéreo para fones e caixas de som.",
  },
  {
    id: "cabo-hdmi",
    name: "Cabo HDMI",
    category: "cabos",
    price: 39.9,
    image: "/assets/img/cabo-hdmi.jpg",
    specs: { tipo: "HDMI" },
    description: "Cabo HDMI para TVs, monitores e consoles.",
  },
  {
    id: "cabo-usbc-usba",
    name: "Cabo USB-C para USB-A",
    category: "cabos",
    price: 29.9,
    image: "/assets/img/cabo-usbc-usba.jpg",
    specs: { tipo: "USB-C / USB-A" },
    description: "Cabo para carregamento e transferência de dados.",
  },
  {
    id: "adaptador-usbc-hdmi",
    name: "Adaptador USB-C para HDMI",
    category: "cabos",
    price: 89.9,
    image: "/assets/img/adaptador-usbc-hdmi.jpg",
    specs: { tipo: "Adaptador" },
    description: "Conecte notebooks USB-C a monitores HDMI.",
  },
  {
    id: "cabo-vga",
    name: "Cabo VGA",
    category: "cabos",
    price: 24.9,
    image: "/assets/img/cabo-vga.jpg",
    specs: { tipo: "VGA" },
    description: "Cabo VGA para monitores e projetores.",
  },

  // ÁUDIO
  {
    id: "fone-tws",
    name: "Fone Bluetooth TWS",
    category: "audio",
    price: 119.9,
    image: "/assets/img/fone-tws-bluetooth.webp",
    specs: { conexao: "Bluetooth" },
    description: "Fone sem fio compacto para uso diário.",
  },
  {
    id: "fone-over-ear",
    name: "Fone Over-Ear Bluetooth",
    category: "audio",
    price: 199.9,
    image: "/assets/img/fone-over-ear-bt.jpg",
    specs: { conexao: "Bluetooth" },
    description: "Conforto e som forte para música e chamadas.",
  },
  {
    id: "fone-in-ear",
    name: "Fone In-Ear com Fio",
    category: "audio",
    price: 29.9,
    image: "/assets/img/fone-p2-in-ear.webp",
    specs: { conexao: "P2" },
    description: "Fone simples e funcional para o dia a dia.",
  },
  {
    id: "headset-usb",
    name: "Headset USB com Microfone",
    category: "audio",
    price: 149.9,
    image: "/assets/img/headset-usb.webp",
    specs: { conexao: "USB" },
    description: "Ideal para reuniões, aulas e trabalho remoto.",
  },
  {
    id: "caixa-som-bt",
    name: "Caixa de Som Bluetooth",
    category: "audio",
    price: 179.9,
    image: "/assets/img/caixa-som-bt.webp",
    specs: { conexao: "Bluetooth" },
    description: "Som portátil para casa e ambientes externos.",
  },
  {
    id: "caixa-som-usb",
    name: "Caixa de Som USB",
    category: "audio",
    price: 79.9,
    image: "/assets/img/caixa-som-usb.jpg",
    specs: { conexao: "USB" },
    description: "Caixa compacta para uso em computador.",
  },

  // PERIFÉRICOS
  {
    id: "teclado-usb",
    name: "Teclado USB",
    category: "perifericos",
    price: 69.9,
    image: "/assets/img/teclado-usb.webp",
    specs: { conexao: "USB" },
    description: "Teclado confortável para trabalho e estudo.",
  },
  {
    id: "mouse-usb",
    name: "Mouse Óptico USB",
    category: "perifericos",
    price: 39.9,
    image: "/assets/img/mouse-usb.webp",
    specs: { conexao: "USB" },
    description: "Mouse preciso e confiável para uso diário.",
  },
  {
    id: "webcam-fullhd",
    name: "Webcam Full HD",
    category: "perifericos",
    price: 159.9,
    image: "/assets/img/webcam-fullhd.webp",
    specs: { resolucao: "Full HD" },
    description: "Webcam ideal para videochamadas e reuniões.",
  },
  {
    id: "hub-usb",
    name: "Hub USB",
    category: "perifericos",
    price: 59.9,
    image: "/assets/img/hub-usb.avif",
    specs: { portas: "4" },
    description: "Expanda as portas USB do seu dispositivo.",
  },

  // ENERGIA
  {
    id: "filtro-linha",
    name: "Filtro de Linha com DPS",
    category: "energia",
    price: 89.9,
    image: "/assets/img/filtro-linha-dps.jpg",
    specs: { protecao: "DPS" },
    description: "Proteção contra surtos elétricos.",
  },
  {
    id: "carregador-usbc",
    name: "Carregador USB-C 25W",
    category: "energia",
    price: 69.9,
    image: "/assets/img/carregador-usbc-25w.webp",
    specs: { potencia: "25W" },
    description: "Carregamento rápido para smartphones.",
  },

  // CUIDADOS
  {
    id: "maquina-barbear",
    name: "Máquina de Barbear",
    category: "cuidados",
    price: 99.9,
    image: "/assets/img/maquina-barbear.jpg",
    specs: { uso: "Barba e cabelo" },
    description: "Praticidade para cuidados pessoais.",
  },
  {
    id: "aparador-pelos",
    name: "Aparador de Pelos",
    category: "cuidados",
    price: 79.9,
    image: "/assets/img/aparador-pelos.webp",
    specs: { uso: "Precisão" },
    description: "Aparador portátil para acabamento.",
  },
];
